services:
  # Backend API Service
  - type: web
    name: ai-stock-advisor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: ai-stock-advisor-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-stock-advisor-backend.onrender.com
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 